name: Test

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: python3.10-alpine3.15
            python_version: "3.10"
          - name: python3.11.0b5-alpine3.16
            python_version: "3.11.0b5"
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: python3.10 -m pip install docker pytest
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
