name: Test

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: python3.13.2-alpine3.21
            python_version: "3.13.2"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: python3.13 -m pip install docker pytest
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
